[package]
name = "amap-example"
version = "0.0.5"
edition = "2024"

[[bin]]
name = "amap"
path = "src/main.rs"

[dependencies]
afaster = { workspace = true, features = ["amap"] }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
