[book]
title = "AFaster Documentation"
authors = ["ahriknow"]
language = "zh"
src = "src"
description = "基于 Rust (afast) 的高性能后端框架"

[rust]
edition = "2024"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/ahriknow/afaster"
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css"]
